apiVersion: v1
kind: Namespace
metadata:
  name: press

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto1
  namespace: press
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto1
  template:
    metadata:
      labels:
        app: proyecto1
    spec:
      containers:
        - name: proyecto1
          image: localhost:32000/proyecto1:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: proyecto1
  namespace: press
spec:
  selector:
    app: proyecto1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto1
  namespace: press
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
    - host: 10.43.103.200.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proyecto1
                port:
                  number: 80
