name: Build and Push to GHCR

on:
  push:
    branches: [ main ]   # o [ dev ] si trabajas en dev

env:
  IMAGE_NAME: proyecto1
  IMAGE_TAG: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push image
        run: |
          docker push ghcr.io/${OWNER_LC}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

